### ISSUE TITLE
Include 'Validate SSL' option for tests

### ISSUE THREAD

**Issue by tdmalone** [terraform-providers/terraform-provider-statuscake#16]
### Terraform Version
```sh
Terraform v0.11.7
+ provider.statuscake v0.2.0
```

### Affected Resource(s)
- [`statuscake_test`](https://www.terraform.io/docs/providers/statuscake/r/test.html)

Thanks for all the additional options added in v0.2.0 of this provider! 😄 

I'd love to also see support for the 'Validate SSL' option:

![image](https://user-images.githubusercontent.com/900469/43309840-3cae1588-91c9-11e8-812c-688ededa7390.png)

**Comment by sryabkov** [comment]
This request seems to be a duplicate for #6

**Comment by tdmalone** [comment]
Thanks @sryabkov, I've +1'ed that issue and closing this one!

**Comment by ivanschwarz** [comment]
I don't think it's a duplicate. This issue reports missing _Validate SSL_ option for uptime tests and #6 reports missing SSL tests. These are two different features of StatusCake.

**Comment by tdmalone** [comment]
Oh, you’re right @ivanschwarz
Thanks so much for working on a PR for this.

**Comment by nh2** [comment]
PR that implements this in #37

**Comment by nh2** [comment]
I've made a prebuilt binary of my PR available here: https://github.com/nh2/terraform-provider-statuscake/releases/tag/nh2fixes-enable_ssl_alert-2019-06-20-2

**Comment by tdmalone** [comment]
This is fixed in #35 which is now merged and due to be released shortly.
Details for release in #38.
