### ISSUE TITLE
Feature request: contact groups

### ISSUE THREAD

**Issue by ndench** [terraform-providers/terraform-provider-statuscake#19]
### Terraform Version
```
Terraform v0.11.10
+ provider.statuscake v0.2.0
```

It would be great if this provider supported creating/updating/deleting contact groups as well. It's supported in the [StatusCake APi](https://www.statuscake.com/api/Contact%20Groups/Add%20or%20Update%20Contact%20Group.md)

**Comment by matschaffer** [comment]
This will be in the next release.

**Comment by matschaffer** [comment]
Will provide updates there via https://github.com/terraform-providers/terraform-provider-statuscake/issues
