### ISSUE TITLE
New argument "accepted_status_codes"

### ISSUE THREAD

**Issue by cazorla19** [terraform-providers/terraform-provider-statuscake#21]
As an alternative to `status_codes` parameter we can implement the `accepted_status_codes` to add only few status code we want to not be triggered on.

For example, that's how it works now if I'd want to have 204 status code being accepted:

```
status_codes = "205, 206, 303, 400, 401, 403, 404, 405, 406, 408, 410, 413, 444, 429, 494, 495, 496, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 521, 522, 523, 524, 520, 598, 599"
```

How could it look like with the parameter `accepted_status_codes`:

```
accepted_status_codes = "200, 204"
```

The parameter `status_codes` should be ingnored if being set together with `accepted_status_codes` one.

**Comment by matschaffer** [comment]
While the status_codes list is a bit of a pain, I'm not sure the TF provider is the place to make this change.

Seems to me the provider/resource should try to avoid diverging from the API (https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md).

**Comment by matschaffer** [comment]
And in thinking about it again, I'm not sure how you'd even want to go about "inverting" the status codes as compared to what statuscake offers. 

Seems like `accepted_status_codes = "200, 204"` might have to be sent to the statuscake API as a full list of the numbers between 100-599 that aren't on that list.

Happy to reconsider given a PR, but closing for now.
