### ISSUE TITLE
Create release for terraform 0.12 support

### ISSUE THREAD

**Issue by AndrewChubatiuk** [terraform-providers/terraform-provider-statuscake#38]
Hi
Can you please create a release with terraform 0.12.x support?
It blocks us from upgrading to a latest terraform version

**Comment by matschaffer** [comment]
Left a few comments on https://github.com/terraform-providers/terraform-provider-statuscake/pull/35#issuecomment-504620971 about that - should be close at hand now.

**Comment by matschaffer** [comment]
1.0.0 is now released with support for terraform 0.12
