### ISSUE TITLE
Error during 'plan': bind: operation not permitted

### ISSUE THREAD

**Issue by vmadman** [terraform-providers/terraform-provider-statuscake#4]
### Terraform Version
```
$ terraform -v
Terraform v0.10.2
```

### Affected Resource(s)
- statuscake
- statuscake_test

### Terraform Configuration Files

These are the _only_ configuration files in my case ..

**statuscake-var-defs.tf**
```hcl
variable "status_cake_username" {}
variable "status_cake_api_key" {}
variable "status_cake_contact_id" {
  default = "12345"
}
```

**statuscake-provider-def.tf**
```hcl
provider "statuscake" {
  username = "${var.status_cake_username}"
  apikey   = "${var.status_cake_api_key}"
}
```

**statuscake-tests.tf**
```hcl
resource "statuscake_test" "api_test_one" {
  website_name = "an_example_api_test"
  website_url  = "www.google.com"
  test_type    = "HTTP"
  check_rate   = 300
  paused       = 0
  timeout      = 20
  contact_id   = "${var.status_cake_contact_id}"
}
```

### Debug Output
https://gist.github.com/vmadman/022ea5af347e7d3160cb6afff0a15c98

### Panic Output
n/a

### Expected Behavior
Terraform should have produced a plan that, if applied, would create a "test" in StatusCake.

### Actual Behavior
I received an error in the console and in the execution log above.

```
Error asking for user input: 1 error(s) occurred:

* provider.statuscake: plugin exited before we could connect
```

### Steps to Reproduce
```
terraform init \
    -var "status_cake_username=<<skuser>>" \
    -var "status_cake_api_key=<<skapikey>>" \
    -var "status_cake_contact_id=<<skcontact>>" \
    "/path/to/project/terraform/resources"
```

.. then ..

```
export TF_LOG="DEBUG"
export TF_LOG_PATH="/path/to/project/terraform/logs/terraform-debug.log"
terraform plan \
    -var "status_cake_username=<<skuser>>" \
    -var "status_cake_api_key=<<skapikey>>" \
    -var "status_cake_contact_id=<<skcontact>>" \
    -state="/path/to/project/terraform/state/default-primary.tfstate" \
    -out="/path/to/project/terraform/plans/default-primary.tfplan" \
    "/path/to/project/terraform/resources"
```

### Important Factoids
n/a

### References
none known

**Comment by vmadman** [comment]
I tried to figure it out on my own and after 5 or 6 hours, I am admitting defeat.

Please let me know if I can provide more information and I appreciate any help that you can give.

**Comment by vmadman** [comment]
Ok, headway ... at least ...

I reduced my semi-sophisticated setup to a single, simple, config and it worked... so, it has to be related to my arrangement of terraform path or variables.

**simple.tf**
```hcl
provider "statuscake" {
  username = "<<skuser>>"
  apikey   = "<<skapikey>>"
}

resource "statuscake_test" "api_test_one" {
  website_name = "an_example_api_test"
  website_url  = "www.google.com"
  test_type    = "HTTP"
  check_rate   = 300
  paused       = 0
  timeout      = 20
  contact_id   = "<<skcontact>>"
}
```

```
  + statuscake_test.api_test_one
      check_rate:   "300"
      contact_id:   "<<skcontact>>"
      paused:       "false"
      test_id:      "<computed>"
      test_type:    "HTTP"
      timeout:      "20"
      trigger_rate: "5"
      website_name: "an_example_api_test"
      website_url:  "www.google.com"

```

.. will post again when I narrow it down.

**Comment by vmadman** [comment]
Ok, I don't really know why, but the problem seems to be related to the fact that I am, actually, using `npm run` to wrap my `terraform` execution script.

So...
```
$ npm run terraform-plan

> my-project@0.1.0 terraform-plan /path/to/project
> ./scripts/terraform/plan.sh
```

.. produces the error, but ...

```
$ scripts/terraform/plan.sh
```

.. does not.  Strange.

For my part, I will just stop using `npm run` as a wrapper, for now, but I'll leave this open just in case anyone might know why this happens.

Thanks!

**Comment by apparentlymart** [comment]
Hi @vmadman! Sorry for this strange behavior.

Usually when we see that particular message is suggests that either the plugin is an older version that is using an older plugin protocol, or that somehow Terraform is confusing a non-plugin executable as a plugin.

However, the following lines in your debug log leads me to suspect that this is a different problem in this case:

```
2017/08/30 05:48:27 [DEBUG] checking for provider in "."
2017/08/30 05:48:27 [DEBUG] checking for provider in "/usr/local/terraform"
2017/08/30 05:48:27 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2017/08/30 05:48:27 [DEBUG] found provider "terraform-provider-statuscake_v0.1.0_x4"
2017/08/30 05:48:27 [DEBUG] found valid plugin: "statuscake"
```

This suggests that the plugin being used is the auto-installed one in `.terraform/plugins/linux_amd64`, which should just be the plugin binary downloaded from [the releases service](https://releases.hashicorp.com/terraform-provider-statuscake/0.1.0/).

It would be helpful to see what output you get if you directly run `.terraform/plugins/linux_amd64/terraform-provider-statuscake_v0.1.0_x4` here. If the plugin is operating correctly, this should give you a message explaining that it's a plugin and thus can't be run directly, but I'm wondering if we'll see some other sort of message about it failing to start up.

**Comment by diegs** [comment]
I'm seeing similar errors when trying to run terraform inside a shell script that's launched from bazel:

```
  3 2017/12/11 20:43:22017-12-11T20:43:22.282Z [DEBUG] plugin: starting plugin: path=/home/diegs/.cache/bazel/_bazel_diegs/a5b6a48c0b880e237b4d4389b47164cc/bazel-sandbox/2643662020267937328/execroot/__main__/_tmp/9e0d72000dcfcfd1904ba5fa13707bb6/cluster/oc-e2e-diegs-test/.terraform/plugins/linux_amd64/terraform-provider-random_v1.0.0_x4 args=[/home/diegs/.cache/bazel/_bazel_diegs/a5b6a48c0b880e237b4d4389b47164cc/bazel-sandbox/2643662020267937328/execroot/__main__/_tmp/9e0d72000dcfcfd1904ba5fa13707bb6/cluster/oc-e2e-diegs-test/.terraform/plugins/linux_amd64/terraform-provider-random_v1.0.0_x4]
  2 2017-12-11T20:43:22.282Z [DEBUG] plugin: waiting for RPC address: path=/home/diegs/.cache/bazel/_bazel_diegs/a5b6a48c0b880e237b4d4389b47164cc/bazel-sandbox/2643662020267937328/execroot/__main__/_tmp/9e0d72000dcfcfd1904ba5fa13707bb6/cluster/oc-e2e-diegs-test/.terraform/plugins/linux_amd64/terraform-provider-random_v1.0.0_x4 
  1 2017-12-11T20:43:22.287Z [DEBUG] plugin.terraform-provider-random_v1.0.0_x4: 2017/12/11 20:43:22 [ERR] plugin: plugin init: listen unix /home/diegs/.cache/bazel/_bazel_diegs/a5b6a48c0b880e237b4d4389b47164cc/bazel-sandbox/2643662020267937328/execroot/__main__/tmp/plugin341735151: bind: invalid argument
  0 2017-12-11T20:43:22.288Z [DEBUG] plugin: plugin process exited: path=/home/diegs/.cache/bazel/_bazel_diegs/a5b6a48c0b880e237b4d4389b47164cc/bazel-sandbox/2643662020267937328/execroot/__main__/_tmp/9e0d72000dcfcfd1904ba5fa13707bb6/cluster/oc-e2e-diegs-test/.terraform/plugins/linux_amd64/terraform-provider-random_v1.0.0_x4
```

The `bind: invalid argument` messages are suspect to me. It seems like it's having trouble creating the client/server plugin connection inside of the subprocess environment, but I can't seem to find the code that tries to setup the plugin RPC to debug further. Any insights on where that lives? Thanks!

**Comment by matschaffer** [comment]
Given the age and that I haven't seen this myself in ~ 6 months of working with the provider fairly heavily, I'm going to close this out.

Feel free to open with fresh details using the 0.2.0 release. It has a few improved error handling points which should help root this out I'd hope.
