### ISSUE TITLE
Tests are being created with empty 'Alert Status Code' value rather than using the api default values

### ISSUE THREAD

**Issue by strebor1982** [terraform-providers/terraform-provider-statuscake#5]
### Terraform Version
0.10.7

### Affected Resource(s)
- statuscake_test

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
variable "status_cake_username" {}
variable "status_cake_api_key" {}

provider "statuscake" {
  username = "${var.status_cake_username}"
  apikey   = "${var.status_cake_api_key}"
}

resource "statuscake_test" "my_test" {
  website_name  = "My test"
  website_url   = "https://www.google.com"
  check_rate    = 300
  test_type     = "HTTP"
  paused        = false
  confirmations = 2
}
```

### Debug Output
[https://gist.github.com/strebor1982/714b15b086c135ad712258acc6225229](https://gist.github.com/strebor1982/714b15b086c135ad712258acc6225229)

### Panic Output
N/A

### Expected Behavior
The default behaviour when creating a status cake test is to create a test with the default Alert Status Codes.  This is confirmed by running a basic request on the status cake api

```bash
curl -X PUT \
  https://app.statuscake.com/API/Tests/Update \
  -H 'api: {apikey}' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'postman-token: 4a8656cc-61a2-af32-a79c-614293ee38fd' \
  -H 'username: {username}' \
  -d 'WebsiteName=MySite&WebsiteURL=http%3A%2F%2Fwww.google.com&CheckRate=300'
  ```  

This will create a test with the default status codes - https://gist.github.com/strebor1982/8db9f314f32ea355075ab815e267845f

### Actual Behavior
Tests are now being created without any Alert status codes 

I have noticed that there was a commit on the status cake client library used by the status cake provider which I think has broken this - https://github.com/DreamItGetIT/statuscake/commit/63610f92274aea0e8a23a225839259d72c1f9d8a

As the statuscake_test has no way of actually setting the status codes via a variable there is no way to correct this behaviour

### Steps to Reproduce
1. `terraform apply`
2. Login to status cake and go to the newly created test
3. Click edit test and scroll down to the 'Alert Status Codes' field.  Field is empty

### Important Factoids
N/A

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/DreamItGetIT/statuscake/commit/63610f92274aea0e8a23a225839259d72c1f9d8a

**Comment by lazzurs** [comment]
👍 Just hit this bug. It is a thing.
