### ISSUE TITLE
Support multiple contact_ids when creating statuscake tests

### ISSUE THREAD

**Issue by tiagoboldt** [terraform-providers/terraform-provider-statuscake#8]
Current StatusCake test configuration only supports one `contact_id`. Statuscake has updated their API to accept a list of contact IDs provided as a string, separating each contact ID with a comma. Terraform should update accordingly.

Please refer to the documentation at: https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md

**Comment by AndorCS** [comment]
It isn't supported via API. (at least for now)

**Comment by tiagoboldt** [comment]
It still shows as available in the docs. The description for the `ContactGroup` field is `A contact group ID assoicated with account to use. Comma separation for multiple ID's.`.

**Comment by AndorCS** [comment]
Yeah, I know. But if you will try API, you will see there is a number.

**Comment by tiagoboldt** [comment]
I'll ask statuscake to participate on this issue 🤞🏻.

**Comment by AndorCS** [comment]
@tiagoboldt you can check this also: https://github.com/DreamItGetIT/statuscake/pull/24

**Comment by StatusCakeDaniel** [comment]
Hi! 

Our API does still support contact group comma separation;

WebsiteName=Google&WebsiteURL=google.com&CheckRate=2&ContactGroup=94372,99925

POST data for example would work; just given that a test now. 

Am I maybe misunderstanding the issue here? Would be happy to help.

**Comment by tiagoboldt** [comment]
Hi @StatusCakeDaniel. This repository dependes on statuscake implementation from DreamItGetIt. I've personally implemented support for handling `ContactGroup` with comma separation, but that was reverted in DreamItGetIT/statuscake#24 as they were having serialization errors from sending a string instead of a number to `ContactGroup`. 

Could you maybe verify if there was any change on your side recently and reopen an issue with https://github.com/DreamItGetIT/statuscake to support string-based `ContactGroup`?

**Comment by AndorCS** [comment]
@StatusCakeDaniel 
Well, from my point of view main issue with Statuscake API is the inconsistency between `receive` API-call about the test and `update/create` API-call.
As an example, there is one numeric field `ContactID` and a list for `ContactGroups` in `Details` API-call and comma-separated list `ContactGroup` in update API-call.

Another example: `tags` field. There is no such field in `Details` API-call, but it exists in `Get All Test`.

These issues make creating libraries significantly harder than it should be.

https://www.statuscake.com/api/Tests/Get%20Detailed%20Test%20Data.md https://www.statuscake.com/api/Tests/Updating%20Inserting%20and%20Deleting%20Tests.md
https://www.statuscake.com/api/Tests/Get%20All%20Tests.md

**Comment by Mustek** [comment]
Going to reopen this for discussion,
On Details:
+ Right now we have an array of strings for Tags (empty array if no tags)
+ Contactgroups is a join with ID, Name and Email
+ ContactID is there for legacy and backwards compatibility and will remain a string with a single Contactgroup ID

On Create/Update:
+ Tags is called TestTags (Can't change naming without affecting bw compat), this expects a comma separated string.
+ ContactGroup also expects a comma separated string of contact IDs

This is the situation as it's locked at the moment. What are your suggestions to make it work for terraform?

**Comment by AndorCS** [comment]
@Mustek if you will just duplicate the functionality of `Get Detailed Test Data` and `Get All Tests` that would be perfect for this library.

We will have the ability to get all the tests with all the settings with one bulk request and after that, we can calculate what we need to change for these tests.

Right now some options are available to read via `/API/Tests/` but more specific options is available only via `/API/Tests/Details/?TestID=[TestID]`. I don't know why it was implemented like that.

And also inconsistency of these API endpoints as I described before.

**Comment by matschaffer** [comment]
If anyone's interested I have multiple test contacts supported in https://github.com/matschaffer/terraform-provider-statuscake/releases/tag/v0.3.0-ms-1

Will look to get it merged and released here as 0.3.0, but will need the client PR to get merged first.
